# Container image that runs your code
FROM python:3.10
ADD . /app
WORKDIR /app

# Install a dependency here directly into our app source dir
# RUN pip install -r requirements.txt

CMD ["python3", "hello_world.py"]
#ENTRYPOINT ["echo pwd"]
