name: My Workflow
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    name: print hello world

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: conduct action1
        id: action1
        uses: ./action1
        with:
          who-to-greet: tt

      - name: Print output
        run: echo "${{ steps.action1.outputs.myprint }}"

